Dev frontend
Oxyto/deno-crud pull request #2
Opened 2022-12-15 13:46 UTC by Oxyto

2022-12-15 14:08 UTC, michaelantounfabernovel commented on islands/answers.tsx
> +async function sendAnswer(
Est-ce qu'on pourrait utiliser `AnswerProp` ici, et rajouter les quelques paramètres qui ne sont pas dans `AnswerProp` ?

Car tu utilises tout `AnswerProp` et quelques propriétés en plus.

2022-12-16 14:23 UTC, gautier-bayle requested changes

2022-12-16 14:23 UTC, gautier-bayle commented on islands/question-list.tsx
> +          <div className="w-64 text-center text-lg text-gray-100">
rajouter une key unique (https://preactjs.com/tutorial/08-keys/)

2022-12-16 14:23 UTC, gautier-bayle commented on islands/question-list.tsx
> +  useEffect(
Ce n'est pas très grave vu que c'est un pour une démo interne, mais fetch dans le useEffect n'est pas un super pattern. Il vaut mieux utiliser des librairies qui gère ça beaucoup mieux en interne (come swr, react-query pour n'en citer que 2)

2022-12-16 14:23 UTC, gautier-bayle commented on islands/questions-answers.tsx
> +                <Answer
idem, rajouter une key

2022-12-16 14:23 UTC, gautier-bayle commented on islands/answers.tsx
> +  setValidate(validate.valid ? "text-green-500" : "text-red-500");
setValidate laisse supposer que tu stockes un booléen. Je pense que tu juste stocker un booléen ici et déplacer ta logique d'affichage directement dans answer. Comme ça les deux sont découplés.

2022-12-16 14:23 UTC, gautier-bayle commented on islands/answers.tsx
> +  const validate = await response.json();
Pas génial comme nom de variable. answerToValidate ?

2022-12-16 14:23 UTC, gautier-bayle commented on islands/answers.tsx
> +  setValidate(validate.valid ? "text-green-500" : "text-red-500");
d'ailleurs, `validate` laisse supposer que c'est une fonction (puisque c'est un verbe). Si c'est un booléan on préférera `[isValidAnswer, setIsValidAnswer]`

2022-12-16 14:23 UTC, gautier-bayle commented on islands/answers.tsx
> +  const [validate, setValidate] = useState<string>();
idem

2022-12-16 14:23 UTC, gautier-bayle commented on routes/api/pick-questions.ts
> +    const questions = getShuffleArray(await getAllQuestions()).slice(0, 10);
je m'interroge un peu sur le format de tes données en BDD. Sur ce endpoint tu réalises 3 appels en DB pour chaque question, soit 30 appels. Pourquoi ne pas stocker les questions et les réponses dans le même document ?

2022-12-16 14:23 UTC, gautier-bayle commented on routes/api/send-answer.ts
>  export const handler: Handlers = {
C'est un bon réflexe d'avoir mis la validation des réponses côté serveur, et de ne pas identifier la bonne réponse côté client. Sinon des petits malins pourraient aller choper la bonne réponse dans les developpers tools ;)

2022-12-19 10:14 UTC, Oxyto commented on islands/answers.tsx
> +  setValidate(validate.valid ? "text-green-500" : "text-red-500");
`validate` n'est pas un booléen mais bien une string puisqu'il contient au départ une string vide, puis l'une des deux autres string. Je l'ai renommé en `valid` pour plus de visibilité

2022-12-19 10:15 UTC, Oxyto commented on islands/question-list.tsx
> +  useEffect(
C'est vrai ! Après c'est plus simple à effectuer pour une démo

2022-12-19 10:19 UTC, Oxyto commented on routes/api/pick-questions.ts
> +    const questions = getShuffleArray(await getAllQuestions()).slice(0, 10);
Je prends en compte ce que tu viens de souligner, cependant je vais l'inclure dans une autre branche

2022-12-19 10:19 UTC, merged